# Assignment Covid

You will learn about combining data with pandas and numpy. Learning outcomes:

- Load a tabular dataset
- Inspect the dataset for quality and metadata information
- Combine data from several tables into one dataframe
- Subselect specific data from dataframes
- Reshape the dataset into a format suitable for visual and statistical analysis


The assignment consists of 6 parts:

- [part 1: load the data](#0)
     - [Exercise 1.1](#ex-11)
- [part 2: data wrangling](#1)
     - [Exercise 2.1](#ex-21)
- [part 3: display data](#2)
     - [Exercise 3.1](#ex-31)


## About the data

The data is generated by Synthea's COVID-19 module. The data was constructed using three peer-reviewed publications published in the early stages of the global pandemic, when less was known, along with emerging resources, data, publications, and clinical knowledge. The simulation outputs synthetic Electronic Health Records (EHR), including the daily consumption of Personal Protective Equipment (PPE) and other medical devices and supplies. For this assignment the `conditions`, `patients`, `observations`, `careplans` and `encounters` table will be used. The Data is stored in separate tables to avoid redundancy, with as a concequence that tables need to be combined and reorganized in dataframes for analysing purpose.

Source: Walonoski J, Klaus S, Granger E, Hall D, Gregorowicz A, Neyarapally G, Watson A, Eastman J. Syntheaâ„¢ Novel coronavirus (COVID-19) model and synthetic data set. Intelligence-Based Medicine. 2020 Nov;1:100007. https://doi.org/10.1016/j.ibmed.2020.100007

Please <a href = "https://storage.googleapis.com/synthea-public/10k_synthea_covid19_csv.zip">download</a> the data

#### Covid Patients
Patients are considered Covid patients if they are identified with `CODE` `840539006`


#### Survivors
Patients that had covid and where tested negative after isolation have tested code `94531-1`,  SARS-CoV-2 RNA Pnl Resp NAA+probe (covid-sars test) + a value of `Not detected (qualifier value)`. These patients are considered to be survived covid patients. 

#### Non-Survivors
Patients that did not survived Covid have a `DEATHDATE` which is not null. 


#### Lab values  COVID-19 patients

Patients are monitored for blood and heart conditions once they are admitted in Hospital or under treatment. The lab values of interest are as follow: 

- `48065-7`  Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma
- `26881-3`   Interleukin 6 [Mass/volume] in Serum or Plasma
- `2276-4` Ferritin [Mass/volume] in Serum or Plasma
- `89579-7` Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method
- `731-0` Lymphocytes [#/volume] in Blood by Automated count
- `14804-9` Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Lactate to pyruvate reaction

---

In [22]:
import pandas as pd
import numpy as np

<a name='0'></a>
## Part 1: Load the data (20 pt)

Instructions: Load the data of the following files

- conditions.csv
- patients.csv
- observations.csv
- careplans.csv
- encounters.csv

Once we read the data we can get familiar with the data. We create some meaningful overviews like 

1. How many patients are there
2. How many covid-patients are there
3. How many patients do have a 'Hospital admission for isolation' encounter


<a name='ex-11'></a>
### 1.1 Code your solution

In [2]:
#YOUR CODE HERE
conditions = ""
patients = ""
observations = ""
care_plans = ""
encounters = ""

### 1.2 Test your solution
The following function needs to be called. You can use this as a test. There are however more meaningful overviews 
you can create.

In [5]:
# - How many patients are there
num_pat = len(set(patients['Id']))
# - How many covid-patients are there
df_cov = conditions[conditions['CODE'] == 840539006].copy() #make a different df for patients with covid
num_cov = len(set(df_cov['PATIENT']))
# - How many patients do have a 'Hospital admission for isolation' encounter
patients_died = patients[~patients['DEATHDATE'].isnull()].copy()
num_died = len(set(patients_died['Id']))
admitted_enco = encounters[encounters['DESCRIPTION'] == 'Hospital admission for isolation (procedure)'].copy()
num_admitted = len(set(admitted_enco['Id']))

def part1(num_pat, num_cov, num_admitted, num_died):
    print(f'There are {num_pat} patients in total')
    print(f'There are {num_cov} covid patients')
    print(f'There are {num_admitted} admitted patients')
    print(f'{num_died} patients died')
    
part1(num_pat, num_cov, num_admitted, num_died)

There are 12352 patients in total
There are 8820 covid patients
There are 1867 admitted patients
2352 patients died

---

<a name='1'></a>
## Part 2: Data Wrangling: set up the dataframe (30 pt)

In this part we are going to combine data to create a dataframe with values of interest for the lab values analysis. 

We would like a dataframe containing the following information per record (only Covid patients!!!)

- `PATIENT` - the ID of the covid patient
- `days` - the number of days the patient is under observation
- `CODE-Y` - the code of the observation  
- `VALUE` - the lab value of the observation

where only the following observation codes needs to be selected:

- `48065-7`  Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma
- `26881-3`   Interleukin 6 [Mass/volume] in Serum or Plasma
- `2276-4` Ferritin [Mass/volume] in Serum or Plasma
- `89579-7` Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method
- `731-0` Lymphocytes [#/volume] in Blood by Automated count
- `14804-9` Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Lactate to pyruvate reaction

The days information is not primarely available and needs to be calculated by substracting observation DATE - START. 

An example of such a dataframe is given below:

                                      days   CODE-Y  VALUE    UNITS
PATIENT                                                            
00079a57-24a8-430f-b4f8-a1cf34f90060   0.0  14804-9  241.8      U/L
00079a57-24a8-430f-b4f8-a1cf34f90060   0.0   2276-4  489.5     ug/L
00079a57-24a8-430f-b4f8-a1cf34f90060   0.0  48065-7    0.4    ug/mL
00079a57-24a8-430f-b4f8-a1cf34f90060   0.0    731-0    1.1  10*3/uL
00079a57-24a8-430f-b4f8-a1cf34f90060   0.0  89579-7    3.4    pg/mL
00079a57-24a8-430f-b4f8-a1cf34f90060   1.0    731-0    1.1  10*3/uL
00079a57-24a8-430f-b4f8-a1cf34f90060   2.0  14804-9  233.7      U/L
00079a57-24a8-430f-b4f8-a1cf34f90060   2.0   2276-4  497.3     ug/L
00079a57-24a8-430f-b4f8-a1cf34f90060   2.0  48065-7    0.3    ug/mL
00079a57-24a8-430f-b4f8-a1cf34f90060   2.0    731-0    1.0  10*3/uL

In [6]:
#Possible approach:

#Combine conditions table (only covid patients, the df_cov) with the patient table into a covid_patient table
#select the only the relevant lab observations from the observations table into a lab_obs table
#merge the covid_patient table with the lab_obs table into a covid_patients_obs table
#clean the covid_patients_obs table (rename columns, select only relevant columns, sort, typecast, add days column)

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
    <ul><li>you can use pandas.DataFrame.merge() to merge dataframes</li>
    <li>df = df[(df.CODE == condition1 | df.CODE == condition1 )] selects rows with CODE of 2 conditional values</li>
    <li>df.DATE - df.START return days if DATE and START are datetime format</li>
    <li>use observations[observations['CODE'].isin(['48065-7','26881-3', '2276-4', '89579-7', '731-0', '14804-9'])] to select the codes</li>
    <li>pd.to_datetime() can be used to typecast to datetime</li>
</ul>
</details>

<a name='ex-21'></a>
### 2.1 Code your solution

In [7]:
#Combine conditions table (only covid patients) with the patient table into a covid_patient table
covid_patient = "your code here"

In [8]:
#select the only the relevant lab observations from the observations table into a lab_obs table (see hints above)
lab_obs = "your code here"

In [9]:
#merge the covid_patient table with the lab_obs table into a covid_patients_obs table
covid_patients_obs = pd.merge(covid_patient, lab_obs, on = 'PATIENT')
covid_patients_obs.head()

,START,STOP,PATIENT,ENCOUNTER_x,CODE_x,DESCRIPTION_x,Id,BIRTHDATE,DEATHDATE,SSN,...,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,DATE,ENCOUNTER_y,CODE_y,DESCRIPTION_y,VALUE,UNITS,TYPE
0,2020-02-19,2020-02-28,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,e3143bce-4a59-40aa-a198-7a9e54077fd8,840539006,COVID-19,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,2019-06-12,NaN,999-81-4349,...,-72.722648,22940.0,893.28,2020-02-19,e97e8d37-7497-4c13-98fd-a4a45655c0bb,731-0,Lymphocytes [#/volume] in Blood by Automated c...,1.1,10*3/uL,numeric
1,2020-02-19,2020-02-28,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,e3143bce-4a59-40aa-a198-7a9e54077fd8,840539006,COVID-19,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,2019-06-12,NaN,999-81-4349,...,-72.722648,22940.0,893.28,2020-02-19,e97e8d37-7497-4c13-98fd-a4a45655c0bb,48065-7,Fibrin D-dimer FEU [Mass/volume] in Platelet p...,0.4,ug/mL,numeric
2,2020-02-19,2020-02-28,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,e3143bce-4a59-40aa-a198-7a9e54077fd8,840539006,COVID-19,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,2019-06-12,NaN,999-81-4349,...,-72.722648,22940.0,893.28,2020-02-19,e97e8d37-7497-4c13-98fd-a4a45655c0bb,2276-4,Ferritin [Mass/volume] in Serum or Plasma,332.4,ug/L,numeric
3,2020-02-19,2020-02-28,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,e3143bce-4a59-40aa-a198-7a9e54077fd8,840539006,COVID-19,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,2019-06-12,NaN,999-81-4349,...,-72.722648,22940.0,893.28,2020-02-19,e97e8d37-7497-4c13-98fd-a4a45655c0bb,89579-7,Troponin I.cardiac [Mass/volume] in Serum or P...,2.3,pg/mL,numeric
4,2020-02-19,2020-02-28,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,e3143bce-4a59-40aa-a198-7a9e54077fd8,840539006,COVID-19,f58bf921-cba1-475a-b4f8-dc6fa3b8f89c,2019-06-12,NaN,999-81-4349,...,-72.722648,22940.0,893.28,2020-02-19,e97e8d37-7497-4c13-98fd-a4a45655c0bb,14804-9,Lactate dehydrogenase [Enzymatic activity/volu...,223.9,U/L,numeric

In [10]:
#clean the covid_patients_obs table (rename columns, select only relevant columns, sort, typecast, add days column)
#to_datetime
covid_patients_obs[['DATE','START']] = covid_patients_obs[['DATE','START']].apply(pd.to_datetime)
#Calculate days between DATE and START
covid_patients_obs['lab_days'] = covid_patients_obs['DATE'] - covid_patients_obs['START']
covid_patients_obs['days'] = covid_patients_obs.lab_days / np.timedelta64(1, 'D')
# covid_patients_obs['days'] = covid_patients_obs['lab_days'].dt.days
#Select columns
covid_patients_obs_clean = covid_patients_obs[['PATIENT', 'days', 'CODE_y', 'VALUE', 'UNITS']]
#rename column
covid_patients_obs_clean = covid_patients_obs_clean.rename(columns={'CODE_y': 'CODE-Y'})
#Set index
covid_patients_obs_clean = covid_patients_obs_clean.set_index('PATIENT')
covid_patients_obs_clean['VALUE'] = covid_patients_obs_clean['VALUE'].astype(float)
covid_patients_obs_clean

                                      days   CODE-Y  VALUE    UNITS
PATIENT
f58bf921-cba1-475a-b4f8-dc6fa3b8f89c   0.0    731-0    1.1  10*3/uL
f58bf921-cba1-475a-b4f8-dc6fa3b8f89c   0.0  48065-7    0.4    ug/mL
f58bf921-cba1-475a-b4f8-dc6fa3b8f89c   0.0   2276-4  332.4     ug/L
f58bf921-cba1-475a-b4f8-dc6fa3b8f89c   0.0  89579-7    2.3    pg/mL
f58bf921-cba1-475a-b4f8-dc6fa3b8f89c   0.0  14804-9  223.9      U/L
...                                    ...      ...    ...      ...
c9699449-7a8b-400a-8e86-fab6aa7134cb   8.0    731-0    0.9  10*3/uL
c9699449-7a8b-400a-8e86-fab6aa7134cb   8.0  48065-7    0.5    ug/mL
c9699449-7a8b-400a-8e86-fab6aa7134cb   8.0   2276-4  525.2     ug/L
c9699449-7a8b-400a-8e86-fab6aa7134cb   8.0  89579-7    3.0    pg/mL
c9699449-7a8b-400a-8e86-fab6aa7134cb   8.0  14804-9  247.9      U/L

[73918 rows x 4 columns]

---

<a name='2'></a>
## Display data (challenge)
<a name='ex-31'></a>
### 3.1 plotting with panel
Create a panel where you can select the code-y column for displaying a plot of days versus value